### ISSUE TITLE
I cannot prevent publishing of PR comment when no tests failed, when generating a failed tests report?

### ISSUE THREAD

**Issue by TylerKasper-Cova** [ctrf-io/github-actions-test-reporter-ctrf#20]
# What
When I generate a failed tests report using github-actions-ctrf
And I use a flag similar to --no-report-on-pass
Then I should not see a PR comment posted to my PR
  
# Why
A PR comment history can become quickly filled with a large number of comments saying "All tests passed" if you have a large number of commits in a draft PR / living PR. In my mind the status check being green is a good enough indicator to say that all of the tests have passed and that the build is safe. 

If this is accomplishable by using another action that then pipes into the `if:` option of the step then adding that to the doc would be sufficient for me.

**Comment by Ma11hewThomas** [comment]
Thanks for the feedback, we have used on-fail-only arg in other libraries, I've added this here too. Published in v0.0.29

**Comment by TylerKasper-Cova** [comment]
Wow, that was very speedy. Thanks for your work! If you have a donate button for your work I'd love to throw a little something your way for the trouble.

**Comment by Ma11hewThomas** [comment]
You're welcome and thank you for the offer, although I won't be taking donations. The best way to help is to share the plugin with those you think it might be useful

Thanks again :)
