### ISSUE TITLE
Display Summary of Skipped Tests

### ISSUE THREAD

**Issue by simontao18** [ctrf-io/github-actions-test-reporter-ctrf#33]
Is there a way to show which tests were skipped? It seems we are able to see that there are skipped tests, but it would be great to know which ones were skipped to make sure no tests were skipped that aren't meant to. Thank you!

**Comment by Ma11hewThomas** [comment]
Nice idea! Published v0.0.41, use [skipped method](https://github.com/ctrf-io/github-actions-test-reporter-ctrf?tab=readme-ov-file#generating-skipped-test-details-table)
