### ISSUE TITLE
Allow different exit codes for test failures

### ISSUE THREAD

**Issue by jhackettns1** [ctrf-io/github-actions-test-reporter-ctrf#36]
When analysing a ctrf file to generate a report, there should be a way to exit with a non-zero exit code if failed tests have been found. 

For now, it generates amazing reports and annotations, but does not actually bubble those failures up to the environment they are running in.

For example:

I have a test suite of 100 tests, and 1 test fails. That failure should cause the entire workflow to be marked as failed, but should still report the failure in a comment or in the summary.

This allows for CI runs that make testing a requirement for merging, imrproving overall automation of the CI stage of development

**Comment by Ma11hewThomas** [comment]
Thanks for your suggestion, I've added the --exit-on-fail argument

published 0.0.43
